spring:
  application:
    name: prova
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: always

logging:
  level:
    root: WARN
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
